-- ur 🤓🤓🤓🤓🤓🤓
-- look at this nerd!
-- really smart
-- never become a skid!!!



























-- Keep for a script!
















































































-- ur really close!

















































































































































-- Never gonna give you up
-- Never gonna let you down
-- Never gonna run around and dessert you









([[This file was protected with MoonSec V3 by Federal#9999]]):gsub('.+', (function(a) _ZWliECyeUlYk = a; end)); return(function(a,...)local o;local d;local h;local s;local e;local r;local n=24915;local t=0;local l={};while t<407 do t=t+1;while t<0x339 and n%0x2d2e<0x1697 do t=t+1 n=(n*649)%35967 local f=t+n if(n%0x426c)>0x2136 then n=(n+0x184)%0x2fff while t<0xb6 and n%0x49b6<0x24db do t=t+1 n=(n+228)%48331 local r=t+n if(n%0x84a)<=0x425 then n=(n+0x1a2)%0x9637 local n=63730 if not l[n]then l[n]=0x1 e={};end elseif n%2~=0 then n=(n+0x1c9)%0x175d local e=69989 if not l[e]then l[e]=0x1 o=string;end else n=(n*0x184)%0xb8d5 t=t+1 local e=1926 if not l[e]then l[e]=0x1 d=getfenv and getfenv();end end end elseif n%2~=0 then n=(n-0x1fa)%0xb962 while t<0x3df and n%0x1fe2<0xff1 do t=t+1 n=(n+277)%36011 local e=t+n if(n%0x1336)<0x99b then n=(n*0x12d)%0x95be local e=61522 if not l[e]then l[e]=0x1 d=(not d)and _ENV or d;end elseif n%2~=0 then n=(n-0x211)%0x801d local e=67470 if not l[e]then l[e]=0x1 s=tonumber;end else n=(n*0x3b7)%0x444f t=t+1 local e=45919 if not l[e]then l[e]=0x1 h="\4\8\116\111\110\117\109\98\101\114\68\97\73\86\81\77\75\70\0\6\115\116\114\105\110\103\4\99\104\97\114\75\68\122\81\71\66\102\80\0\6\115\116\114\105\110\103\3\115\117\98\119\100\80\120\82\81\114\82\0\6\115\116\114\105\110\103\4\98\121\116\101\120\114\99\101\105\105\102\116\0\5\116\97\98\108\101\6\99\111\110\99\97\116\118\95\100\122\106\116\114\105\0\5\116\97\98\108\101\6\105\110\115\101\114\116\73\70\112\85\99\82\75\97\5";end end end else n=(n-0x2a3)%0x27bc t=t+1 while t<0x278 and n%0x4534<0x229a do t=t+1 n=(n*313)%42083 local h=t+n if(n%0x1c4a)>=0xe25 then n=(n-0x2df)%0x193a local e=51331 if not l[e]then l[e]=0x1 end elseif n%2~=0 then n=(n+0x2bf)%0x816f local n=55648 if not l[n]then l[n]=0x1 r=function(t)local n=0x01 local function l(e)n=n+e return t:sub(n-e,n-0x01)end while true do local t=l(0x01)if(t=="\5")then break end local n=o.byte(l(0x01))local n=l(n)if t=="\2"then n=e.DaIVQMKF(n)elseif t=="\3"then n=n~="\0"elseif t=="\6"then d[n]=function(n,e)return a(8,nil,a,e,n)end elseif t=="\4"then n=d[n]elseif t=="\0"then n=d[n][l(o.byte(l(0x01)))];end local t=l(0x08)e[t]=n end end end else n=(n*0x295)%0x661 t=t+1 local e=67392 if not l[e]then l[e]=0x1 end end end end end n=(n-970)%32963 end r(h);local t={};for n=0x0,0xff do local e=e.KDzQGBfP(n);t[n]=e;t[e]=n;end local function u(e)return t[e];end local h=(function(f,o)local h,l=0x01,0x10 local t={{},{},{}}local d=-0x01 local n=0x01 local r=f while true do t[0x03][e.wdPxRQrR(o,n,(function()n=h+n return n-0x01 end)())]=(function()d=d+0x01 return d end)()if d==(0x0f)then d=""l=0x000 break end end local d=#o while n<d+0x01 do t[0x02][l]=e.wdPxRQrR(o,n,(function()n=h+n return n-0x01 end)())l=l+0x01 if l%0x02==0x00 then l=0x00 e.IFpUcRKa(t[0x01],(u((((t[0x03][t[0x02][0x00]]or 0x00)*0x10)+(t[0x03][t[0x02][0x01]]or 0x00)+r)%0x100)));r=f+r;end end return e.v_dzjtri(t[0x01])end);r(h(163,"prJ<6FKCVYt#2zT=F=#=6VtF!<K<2JF#Y TT6G#<rTCF#6zJJT#tF<#{T<KK2C=tCTTCzrJz#t6T#2=O6zz<=YCT#Cz(JT##rCC<TFKzY#==VFzz<zYCVYTCC<zJJzt#,6K#zC<VYV=<FC6JtJJ#V#TY6Ft<<6Y2zJ<Jt5gzKztt#Fr6YT==Ft#VJJt6=FC*YYr2CY262#JY#trKC6=6KKYF9YCFz=6MVTV6TJC<zhJCtwrTKC#60TVC=CFr<zYzJCVJTn6<YY<JVz2V<FC2ztKO###{1TYY=KF<zVJrtYTVFC##X6F6KY2CFJ#<rJVzzVF6Y=T=F6zo<6JJVJQ#Kz2#JtC==V62z6<CKJTCF<ttYF=6CTzT<VY6JFY7TortYVzTFFVzt#PYYt=xFJTt6FY#zT6J#2TzFKK62JFJ#rPKVtT<F<tYTVC#tYJYrzCz*VKV26rzCtr2FK26<FK###<tt6YQTTCtzV<6zKrrK=TC<zC2zzFJ6YtC<VYCT#CCTV62C2=rFtY#TY%JKJTz6Vt2yVK<zF6rt2 T6CtJ=TKFCFz6FT##rVC6eYF32Vr7FtzYrTYYV#TYCVzF<J#=w=FVzkJ=t%2=<K66tJ<<VTT#CT26HTK=T=FttTdu=zFzTC6ttKyJF#TCFrYJWz<=YY=FKFC82TF2#zrKYWTYK>tVr=F##Cr=JYVCrtCrz6KK25r<KJzJJtK2zJTJ6r22JTV6TrF:zCr=YC=KF&VKz2=VFCTr6<Y2=zYFza6Jt#UF6VY==rWTK2=TF6#<6FVJ=K6#trr6C<z 2CJF#VrJK=TrK##<JJ62#JrrC#V0TQKY2#J6VCzTK=z2<dC=2t6zCV=2=<6=zTV{zzczYczzJrYFu2=J6Tz2K#tzgYC6=r6CYCTJ=r6zzzKV2#JtCJ#=J6VVzt=562zzCJt=<AKT2JJ=YVzrT=6#zzKt2#IFF22TJ6tJ=#TT62zV<VYKJFV=T26YVr=r6<YttC?6YrT2V##Y6VCrqr<##V=KL<KkTT6t#zJ6C5T<6#VzrzCVF=#26YtFrFV6TrKrt#-6C<26##rVtKurt6Tr<6t2!C6t2TrtrCCKxrF2#zrzYV_rF=2KRYKY2YrzJzV2rKCJzrJ=tY3tV;TK TY=zzJ#6<t+<AVt=YVF2T<=YF=YF2tTY==2VVTtCT26rtK22KFtYJrF=#FVTF6VTrg2Yz2262t2TtKCFC#66<Y=JVK#zK6Yt#GF6YYF#<r7tJ=#YC=YJFCT=JK8Y#fJ_=K2=VF#TVFrVF V66#t=<CFK#2VFt#6JTYzw2F=t<DCCV2t2CJ6#<%zY<lC6F#r=VKY2zr6JK"));r(h(222,"Vx#0 )Rr_3OCut.p## Ot3puxu0))urr0RC_.Cn)#O#p)x_tC0Ot.pnxx p4x0O8C)t)P##  0R _OOCOt.C<txp.Cxx3.u#tCv##O #r#rtOuC).rx) a._xv3pu#.#pC##0tpt_r3tt#.0&O#t 3 uR.30Cr.p#3t pO_)3Ct*.RO)#. _RCO>COtr.0# x.  _COtOp_eOO00 rr_30Ott..t##0x) _?3CO3u9xdx)#O) 3xOCRu3xL#00)0_RO0u_OCtt#x0)RtRRCxtRttO.tnR)rx3Cu_. pCp.))rRR OOt.__O3a003)33rOxu .u#u C{G#RC txprxO0O)0rO3)Cu. ?upr03R0RrO3R*_rx_#r OrR3x) .)X;# 0r)C_)C#uCpP.ux)0#Rr_.)lr 1)#q  )rrCO)umupx)#p#3r.3CCurS30#d  )t_ OuO3.pp 0R#3).ru3 R.3##x0)).r333uuu3x)S. 3R03.CxC._OCs0C)x_R3u)Ct.zR#C tr#ROC)tpup# <.)pRp0r"));local n=(-e.sKLAWe_A+(function()local r,n=e.llBhlBiu,e.hyPPyBjF;(function(n,e,l,t)t(l(l,t,e,n),e(n,e,n,n)and e(t,e,e and e,e),t(n,l,e,n),t(t and e,e,n,n))end)(function(o,l,t,d)if r>e.FqBIrmpm then return l end r=r+e.hyPPyBjF n=(n-e.SOYhlomt)%e.itMPaqtT if(n%e.AfZxDjjX)>=e.ZoAXgtxi then n=(n+e.MnZJGcvs)%e.ljHXBClj return t(l(t and t,d,t,o),l(d and d,o,o,t)and d(o,d,d,t),t(d,l,t,l),d(t,l,t and l,t))else return l end return l end,function(o,l,d,t)if r>e.YEpRdkWJ then return d end r=r+e.hyPPyBjF n=(n-e.UCbPCKjq)%e.MDouCkzt if(n%e.dreBcLfA)<e.pngMTqEQ then n=(n+e.WSf_AwHk)%e.vSdxQDfs return l else return l(l(t,t,t and l,l),o(l,l and t,t,t),t(l,d,t,t),o(t,o,o,d))end return d(t(d,o,l,l),o(o,t,d,l),d(d and d,o,d,l),o(t,t,d,l)and t(o,l,t,d))end,function(d,o,l,t)if r>e.wUVqjLPh then return l end r=r+e.hyPPyBjF n=(n+e._szMeqUF)%e.JYglHFEO if(n%e.hRmXEgOm)<e.eXD_auGQ then n=(n*e.kTAEhvmb)%e.anRpEBAT return o else return d(d(t,t,d,l),l(d,t,l,t),o(o,d,d,o),d(t,l,o,t))end return t(d(o,t,d and t,t and l),d(l,l and t,t,t)and o(t,t and o,l,l),d(d,o,o,l),l(l,o,d,t))end,function(t,o,l,d)if r>e.QMgRlKJU then return d end r=r+e.hyPPyBjF n=(n-e.nkaSfaFO)%e.BlWrtqJC if(n%e.qOdpmSMB)<e.hH_WPfhh then n=(n*e.KxcuBKMZ)%e.fvm_MsAh return t(d(l,o,l and o,t),l(t,t,l,t),l(o,o,d,d),t(t and t,d,l,l))else return o end return d end)return n;end)())local le=(getfenv)or(function()return _ENV end);local f=e.dQumExsr or e.vmpJQL_d;local m=e.hyPPyBjF;local d=e.xxKqaH_y;local l=e.dIHVvobP;local u=e.bhjUEMTI;local function ee(_,...)local h=h(n,"fhR#FsGP_I1=vg6Q_1&G_I!vIhhvIsh_I=_1h/_s{=IgRh1Rhv1FRb#6v#FRvsF_#R1Q#6=IgIGPggGp6#vsF#v#s=g=#1==PF6#sGQ%GdQs8QIPh#IGhI6FI#hGIs6QI%RR##Qs#P=1#gR_=P#1=I#Q_Izh_FF1=vss_QF=gEs6gsGsgsG=6vGhQhGsQFPGQQP#QQ__vsPg}v_ggR_P3QIPhh1hRI1vRF1vR_P#Q_P1Q6PQF.=PFRv156gwF1gQshgPsggIRs6GPR6h^s=guI_vBQ6GPg9h_6=6_P<gI#XQFgRPIFRIsIRv=h#h=IRg16FR=G#_PPshvGsFv=TG=Gs=g6G{v_sgg6h6gP#P1PGveG#KgIP=Qg_hhh_#hhF=6FGP61Gg=Is#=gF8v#I##_==#g1s#1==#1=hssgGsSg_sF6##=gQsg6DGFQ9FGQvPQn&hhIFhPI1Rv1dR#1GRI=6RQ=R#s=I#==6FhgGsvv1FggDs1gGsIgvPh6=Gs6_G=QhPhQFPPRM_gD5_#LG_QSvIShRI=h_IQRg1hRF1P#V1g#h=##1v_#v=QFRvvF_vvF6ghsIgPs1ggGh6#GG6IP6c#PRQsP_QvP69h_FhII=rgIhh#I_hIIvhQvR#g1_Rv16#R=F#==1FQgsF#vIFIghFQgRssg_GGg6GR6FG161GgQcP#?=PIQvPQKR_sB1_=T611hFIPh1I6Rt1FRG1I#=1Q#R=s#I==#6vhFF");local t=e.llBhlBiu;e.ihlkKggW(function()e.ncDyxDhz()t=t+e.hyPPyBjF end)local function n(n,e)if e then return t end;t=n+t;end local r,t,c=a(e.llBhlBiu,a,n,h,e.xrceiift);local function o()local l,t=e.xrceiift(h,n(e.hyPPyBjF,e.xxKqaH_y),n(e.mMqRIYeA,e.fjGAVOpl)+e.dIHVvobP);n(e.dIHVvobP);return(t*e.huuuPcXR)+l;end;local z=true;local z=e.llBhlBiu local function g()local n=t();local t=t();local d=e.hyPPyBjF;local l=(r(t,e.hyPPyBjF,e.rCuAtQqR)*(e.dIHVvobP^e.HRAWbGzx))+n;local n=r(t,e.DVVyfbth,e.wWMhfLsb);local t=((-e.hyPPyBjF)^r(t,e.HRAWbGzx));if(n==e.llBhlBiu)then if(l==z)then return t*e.llBhlBiu;else n=e.hyPPyBjF;d=e.llBhlBiu;end;elseif(n==e.UablRUXO)then return(l==e.llBhlBiu)and(t*(e.hyPPyBjF/e.llBhlBiu))or(t*(e.llBhlBiu/e.llBhlBiu));end;return e.kUtLPuuU(t,n-e.PTmvAuVG)*(d+(l/(e.dIHVvobP^e.Ds_slsyn)));end;local b=t;local function y(t)local l;if(not t)then t=b();if(t==e.llBhlBiu)then return'';end;end;l=e.wdPxRQrR(h,n(e.hyPPyBjF,e.xxKqaH_y),n(e.mMqRIYeA,e.fjGAVOpl)+t-e.hyPPyBjF);n(t)local n=""for t=(e.hyPPyBjF+z),#l do n=n..e.wdPxRQrR(l,t,t)end return n;end;local b=#e.lrxAaiKk(s('\49.\48'))~=e.hyPPyBjF local n=t;local function k(...)return{...},e.OyPiazkV('#',...)end local function ne()local s={};local h={};local n={};local z={s,h,nil,n};local n=t()local f={}for d=e.hyPPyBjF,n do local l=c();local t;if(l==e.llBhlBiu)then t=(c()~=#{});elseif(l==e.hyPPyBjF)then local n=g();if b and e.icDDGI_w(e.lrxAaiKk(n),'.(\48+)$')then n=e.HqyGzBq_(n);end t=n;elseif(l==e.dIHVvobP)then t=y();end;f[d]=t;end;for n=e.hyPPyBjF,t()do h[n-(#{e.hyPPyBjF})]=ne();end;for z=e.hyPPyBjF,t()do local n=c();if(r(n,e.hyPPyBjF,e.hyPPyBjF)==e.llBhlBiu)then local h=r(n,e.dIHVvobP,e.xxKqaH_y);local a=r(n,e.bhjUEMTI,e.fjGAVOpl);local n={o(),o(),nil,nil};if(h==e.llBhlBiu)then n[d]=o();n[u]=o();elseif(h==#{e.hyPPyBjF})then n[d]=t();elseif(h==_[e.dIHVvobP])then n[d]=t()-(e.dIHVvobP^e.mVODAxSy)elseif(h==_[e.xxKqaH_y])then n[d]=t()-(e.dIHVvobP^e.mVODAxSy)n[u]=o();end;if(r(a,e.hyPPyBjF,e.hyPPyBjF)==e.hyPPyBjF)then n[l]=f[n[l]]end if(r(a,e.dIHVvobP,e.dIHVvobP)==e.hyPPyBjF)then n[d]=f[n[d]]end if(r(a,e.xxKqaH_y,e.xxKqaH_y)==e.hyPPyBjF)then n[u]=f[n[u]]end s[z]=n;end end;z[e.xxKqaH_y]=c();return z;end;local function ee(l,n,t)local d=n;local d=t;return s(e.icDDGI_w(e.icDDGI_w(({e.ihlkKggW(l)})[e.dIHVvobP],n),t))end local function te(b,n,c)local function ee(...)local o,p,z,j,s,t,h,g,_,y,ee,n;local r=e.llBhlBiu;while-e.hyPPyBjF<r do if r<=e.dIHVvobP then if e.llBhlBiu>=r then o=a(e.fjGAVOpl,e.tBvHknOo,e.hyPPyBjF,e._ESinkRA,b);p=a(e.fjGAVOpl,e.rwFBYjHR,e.dIHVvobP,e.gsJpOhDi,b);else if r>-e.dIHVvobP then for n=e._ESinkRA,e.QcukRYmb do if r~=e.hyPPyBjF then t=-e.ZqRaK_fP;h=-1;break;end;z=a(6,98,3,69,b);s=k j=0;break;end;else t=-41;h=-1;end end else if r<=4 then if r~=4 then g={};_={...};else y=e.OyPiazkV('#',...)-1;ee={};end else if 5~=r then r=-2;else n=a(7);end end end r=r+1;end;for e=0,y do if(e>=z)then g[e-z]=_[e+1];else n[e]=_[e+1];end;end;local e=y-z+1 local e;local r;local function a(...)while true do end end while true do if t<-40 then t=t+42 end e=o[t];r=e[m];if r<12 then if r>5 then if r>8 then if r>=10 then if r~=6 then for t=30,86 do if r<11 then n[e[l]]();break;end;local o,f,h,a,r;local t=0;while t>-1 do if t>2 then if 5<=t then if t>=4 then for e=36,83 do if 5~=t then t=-2;break;end;n(r,a);break;end;else n(r,a);end else if 0<=t then repeat if 3~=t then r=o[f];break;end;a=o[h];until true;else r=o[f];end end else if t<1 then o=e;else if 0~=t then repeat if t~=2 then f=l;break;end;h=d;until true;else h=d;end end end t=t+1 end break;end;else n[e[l]]();end else if(n[e[l]]==e[u])then t=t+1;else t=e[d];end;end else if r>=7 then if r>5 then for t=42,91 do if 8>r then local t=e[l];local l=n[e[d]];n[t+1]=l;n[t]=l[e[u]];break;end;local t=e[l]local l,e=s(n[t](f(n,t+1,e[d])))h=e+t-1 local e=0;for t=t,h do e=e+1;n[t]=l[e];end;break;end;else local t=e[l]local l,e=s(n[t](f(n,t+1,e[d])))h=e+t-1 local e=0;for t=t,h do e=e+1;n[t]=l[e];end;end else c[e[d]]=n[e[l]];end end else if 2<r then if 4<=r then if r>=3 then repeat if 4~=r then do return end;break;end;local l=e[l];local t=n[e[d]];n[l+1]=t;n[l]=t[e[u]];until true;else local t=e[l];local l=n[e[d]];n[t+1]=l;n[t]=l[e[u]];end else n[e[l]]=(e[d]~=0);end else if 0>=r then local e=e[l]n[e]=n[e](f(n,e+1,h))else if-1~=r then repeat if 2~=r then n[e[l]]=(e[d]~=0);break;end;n[e[l]]();until true;else n[e[l]]();end end end end else if r<18 then if r>14 then if r<=15 then t=e[d];else if r~=13 then repeat if 17>r then local e=e[l]n[e]=n[e](f(n,e+1,h))break;end;local a,g,z,k,b,y,m,r,p,j,_;n[e[l]]=c[e[d]];t=t+1;e=o[t];a=e[l];g=n[e[d]];n[a+1]=g;n[a]=g[e[u]];t=t+1;e=o[t];r=0;while r>-1 do if r>=3 then if 4>=r then if r>1 then for e=25,93 do if r<4 then y=z[b];break;end;m=z[k];break;end;else y=z[b];end else if r<6 then n(m,y);else r=-2;end end else if 0<r then if r>=-3 then repeat if 2~=r then k=l;break;end;b=d;until true;else k=l;end else z=e;end end r=r+1 end t=t+1;e=o[t];a=e[l]p,j=s(n[a](f(n,a+1,e[d])))h=j+a-1 _=0;for e=a,h do _=_+1;n[e]=p[_];end;t=t+1;e=o[t];a=e[l]n[a]=n[a](f(n,a+1,h))t=t+1;e=o[t];n[e[l]]();t=t+1;e=o[t];do return end;until true;else local a,g,z,y,b,k,j,r,m,p,_;n[e[l]]=c[e[d]];t=t+1;e=o[t];a=e[l];g=n[e[d]];n[a+1]=g;n[a]=g[e[u]];t=t+1;e=o[t];r=0;while r>-1 do if r>=3 then if 4>=r then if r>1 then for e=25,93 do if r<4 then k=z[b];break;end;j=z[y];break;end;else k=z[b];end else if r<6 then n(j,k);else r=-2;end end else if 0<r then if r>=-3 then repeat if 2~=r then y=l;break;end;b=d;until true;else y=l;end else z=e;end end r=r+1 end t=t+1;e=o[t];a=e[l]m,p=s(n[a](f(n,a+1,e[d])))h=p+a-1 _=0;for e=a,h do _=_+1;n[e]=m[_];end;t=t+1;e=o[t];a=e[l]n[a]=n[a](f(n,a+1,h))t=t+1;e=o[t];n[e[l]]();t=t+1;e=o[t];do return end;end end else if r>=13 then if r>=12 then repeat if 14~=r then do return end;break;end;c[e[d]]=n[e[l]];until true;else do return end;end else local t=e[l]local l,e=s(n[t](f(n,t+1,e[d])))h=e+t-1 local e=0;for t=t,h do e=e+1;n[t]=l[e];end;end end else if r<21 then if r<=18 then for r=0,3 do if 2<=r then if 2~=r then if(n[e[l]]==e[u])then t=t+1;else t=e[d];end;else n[e[l]]=c[e[d]];t=t+1;e=o[t];end else if-3<r then for h=31,55 do if r<1 then n[e[l]]=(e[d]~=0);t=t+1;e=o[t];break;end;c[e[d]]=n[e[l]];t=t+1;e=o[t];break;end;else c[e[d]]=n[e[l]];t=t+1;e=o[t];end end end else if r>=18 then for t=42,81 do if r~=20 then local h,o,a,f,r;local t=0;while t>-1 do if 2>=t then if t>0 then if-3<=t then repeat if t>1 then a=d;break;end;o=l;until true;else o=l;end else h=e;end else if t<5 then if t>=2 then for e=21,54 do if t~=3 then r=h[o];break;end;f=h[a];break;end;else r=h[o];end else if t>=4 then for e=17,52 do if t~=6 then n(r,f);break;end;t=-2;break;end;else n(r,f);end end end t=t+1 end break;end;n[e[l]]=c[e[d]];break;end;else local r,o,a,f,h;local t=0;while t>-1 do if 2>=t then if t>0 then if-3<=t then repeat if t>1 then a=d;break;end;o=l;until true;else o=l;end else r=e;end else if t<5 then if t>=2 then for e=21,54 do if t~=3 then h=r[o];break;end;f=r[a];break;end;else h=r[o];end else if t>=4 then for e=17,52 do if t~=6 then n(h,f);break;end;t=-2;break;end;else n(h,f);end end end t=t+1 end end end else if 22<=r then if 23>r then t=e[d];else n[e[l]]=c[e[d]];end else if(n[e[l]]==e[u])then t=t+1;else t=e[d];end;end end end end t=1+t;end;end;return ee end;local d=0xff;local a={};local h=(1);local r='';(function(t)local l=t local o=0x00 local n=0x00 l={(function(f)if o>0x2c then return f end o=o+1 n=(n+0xdb4-f)%0x34 return(n%0x03==0x1 and(function(e)if not t[e]then n=n+0x01 t[e]=(0x6b);end return true end)'CanoJ'and l[0x1](0x309+f))or(n%0x03==0x2 and(function(e)if not t[e]then n=n+0x01 t[e]=(0x97);end return true end)'XHcuD'and l[0x3](f+0x390))or(n%0x03==0x0 and(function(l)if not t[l]then n=n+0x01 t[l]=(0x13);r={r..'\58 a',r};a[h]=ne();h=h+((not e.SSmqIiYJ)and 1 or 0);r[1]='\58'..r[1];d[2]=0xff;end return true end)'HGBsb'and l[0x2](f+0x111))or f end),(function(e)if o>0x30 then return e end o=o+1 n=(n+0x12a8-e)%0x40 return(n%0x03==0x2 and(function(e)if not t[e]then n=n+0x01 t[e]=(0x5f);a[h]=le();h=h+d;end return true end)'Qygcf'and l[0x3](0x1ba+e))or(n%0x03==0x1 and(function(e)if not t[e]then n=n+0x01 t[e]=(0x1c);d[2]=(d[2]*(ee(function()a()end,f(r))-ee(d[1],f(r))))+1;a[h]={};d=d[2];h=h+d;end return true end)'wbUbP'and l[0x2](e+0x288))or(n%0x03==0x0 and(function(e)if not t[e]then n=n+0x01 t[e]=(0xbd);r='\37';d={function()d()end};r=r..'\100\43';end return true end)'xExHF'and l[0x1](e+0x345))or e end),(function(e)if o>0x26 then return e end o=o+1 n=(n+0x671-e)%0xc return(n%0x03==0x2 and(function(e)if not t[e]then n=n+0x01 t[e]=(0xa8);end return true end)'TmftO'and l[0x1](0x1f7+e))or(n%0x03==0x0 and(function(e)if not t[e]then n=n+0x01 t[e]=(0x20);end return true end)'ywVsM'and l[0x2](e+0xd4))or(n%0x03==0x1 and(function(e)if not t[e]then n=n+0x01 t[e]=(0xf5);end return true end)'UiRkR'and l[0x3](e+0x2d5))or e end)}l[0x2](0xc8a)end){};local e=te(f(a));return e(...);end return ee((function()local t={}local n=0x01;local l;if e.SSmqIiYJ then l=e.SSmqIiYJ(ee)else l=''end if e.icDDGI_w(l,e.jxanUeqz)then n=n+0;else n=n+1;end t[n]=0x02;t[t[n]+0x01]=0x03;return t;end)(),...)end)((function(t,e,n,d,l,r)local r;if 3<t then if 6>t then if 0~=t then repeat if t~=4 then local t=d;do return function()local e=e(n,t(t,t),t(t,t));t(1);return e;end;end;break;end;local t=d;local r,d,l=l(2);do return function()local e,n,h,o=e(n,t(t,t),t(t,t)+3);t(4);return(o*r)+(h*d)+(n*l)+e;end;end;until true;else local t=d;local o,h,l=l(2);do return function()local r,d,e,n=e(n,t(t,t),t(t,t)+3);t(4);return(n*o)+(e*h)+(d*l)+r;end;end;end else if t<7 then do return l[n]end;else if 7~=t then do return n(t,nil,n);end else do return setmetatable({},{['__\99\97\108\108']=function(e,t,d,l,n)if n then return e[n]elseif l then return e else e[t]=d end end})end end end end else if 2>t then if 1~=t then do return e(1),e(4,l,d,n,e),e(5,l,d,n)end;else do return function(t,e,n)if n then local e=(t/2^(e-1))%2^((n-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(t%(e+e)>=e)and 1 or 0;end;end;end;end else if 1<t then for r=20,77 do if t<3 then do return 16777216,65536,256 end;break;end;do return e(1),e(4,l,d,n,e),e(5,l,d,n)end;break;end;else do return e(1),e(4,l,d,n,e),e(5,l,d,n)end;end end end end),...)